name: tea_talk_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.1.2
  http: ^0.13.6
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.3
  uuid: ^4.0.0
  pointycastle: ^3.7.3
  convert: ^3.0.1
  random_string: ^2.3.1
  mime: ^1.0.5
  http_parser: ^4.0.2
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8   

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
